### ISSUE TITLE
Unknown property: "getSelectedVertices" in #Struct:skinOps() with 'Find wights conflict' utility

### ISSUE THREAD

**Issue by Tosyk** [pudingus/Max4dsTools#5]
hi. the script is great. I was able to skin character and put into the game just in 2 evenings.
now I want to improve the skin but when I try to use 'Find wights conflict' utility I'm getting this error over and over:
[skin_weigths_error.txt](https://github.com/pudingus/Max4dsTools/files/7117826/skin_weigths_error.txt)

maybe I don't use it right?

**Comment by pudingus** [comment]
I will take a look at it

**Comment by pudingus** [comment]
It's fixed in version 0.8.3
